# Generated by Django 5.0.6 on 2024-07-11 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_qarz_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qarz',
            name='is_sana',
        ),
    ]
