# Generated by Django 5.0.6 on 2024-09-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_qarz_is_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qarz',
            name='summa',
            field=models.PositiveIntegerField(),
        ),
    ]
